global:
  scrape_interval: 15s

scrape_configs:
  # FastApi 애플리케이션의 메트릭 수집
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi-app:5001']  # Docker for Mac/Windows인 경우; 리눅스에서는 'localhost:5000' 또는 컨테이너 네트워크 이름 사용

  # 시스템 메트릭 수집 (node-exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  # cadvisor 시스템 메트릭 수집 (cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  # loki 메트릭 수집
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]          # Docker Compose 내 서비스 이름과 포트